export const BLOG_APP_PATH = "/admin/automatic-blog";
export const BLOG_PUBLIC_PATH = "/blog";

export const BLOG_STATUSES = [
  "IDEA",
  "TOPIC_REVIEW",
  "BRIEF_GENERATING",
  "BRIEF_READY",
  "RESEARCHING",
  "RESEARCH_READY",
  "OUTLINING",
  "DRAFTING",
  "PRACTICAL_REVIEW",
  "EMPATHY_REVIEW",
  "EDITING",
  "NATURAL_VOICE_REVIEW",
  "SEO_REVIEW",
  "FACT_CHECK",
  "BRAND_REVIEW",
  "IMAGE_SELECTION",
  "IMAGE_REVIEW",
  "HUMAN_REVIEW",
  "NEEDS_CHANGES",
  "APPROVED",
  "SCHEDULED",
  "PUBLISHING",
  "PUBLISHED",
  "FAILED",
  "ARCHIVED"
] as const;

export type BlogStatus = (typeof BLOG_STATUSES)[number];

export const BLOG_NAV_PAGES = [
  { id: "overview", label: "Overview", permission: "blog.view" },
  { id: "calendar", label: "Content Calendar", permission: "blog.view" },
  { id: "generate", label: "Generate Article", permission: "blog.create" },
  { id: "topics", label: "Topic Ideas", permission: "blog.view" },
  { id: "briefs", label: "Briefs", permission: "blog.view" },
  { id: "research", label: "Research", permission: "blog.manage_sources" },
  { id: "drafts", label: "Drafts", permission: "blog.edit" },
  { id: "human-review", label: "Human Review", permission: "blog.review" },
  { id: "needs-approval", label: "Needs Approval", permission: "blog.approve" },
  { id: "scheduled", label: "Scheduled", permission: "blog.schedule" },
  { id: "published", label: "Published", permission: "blog.view" },
  { id: "failed", label: "Failed", permission: "blog.view" },
  { id: "archived", label: "Archived", permission: "blog.archive" },
  { id: "pillars", label: "Content Pillars", permission: "blog.manage_brand" },
  { id: "knowledge", label: "Fitdog Knowledge Base", permission: "blog.manage_knowledge" },
  { id: "media", label: "Media Library", permission: "blog.manage_media" },
  { id: "image-approvals", label: "Image Approvals", permission: "blog.approve_images" },
  { id: "sources", label: "Sources", permission: "blog.manage_sources" },
  { id: "publishing", label: "Publishing Connections", permission: "blog.manage_publishing" },
  { id: "providers", label: "AI Providers", permission: "blog.manage_providers" },
  { id: "brand-voice", label: "Brand Voice", permission: "blog.manage_brand" },
  { id: "editorial", label: "Editorial Standards", permission: "blog.manage_brand" },
  { id: "automation", label: "Automation Rules", permission: "blog.manage_automation" },
  { id: "analytics", label: "Analytics", permission: "blog.view_analytics" },
  { id: "costs", label: "Cost and Usage", permission: "blog.view_costs" },
  { id: "audit", label: "Audit Log", permission: "blog.view_audit_log" },
  { id: "settings", label: "Settings", permission: "blog.manage_automation" },
  { id: "setup", label: "Setup Wizard", permission: "blog.manage_providers" },
  { id: "editor", label: "Article Editor", permission: "blog.edit" }
] as const;

export type BlogPageId = (typeof BLOG_NAV_PAGES)[number]["id"];

export const BLOG_TONE_PRESETS = [
  "new_puppy_support",
  "training_advice",
  "health_conscious_guidance",
  "boarding_preparation",
  "daycare_education",
  "grooming_guidance",
  "seasonal_safety",
  "local_dog_owner_guide",
  "sensitive_owner_concern",
  "service_explanation",
  "member_story",
  "light_community_article",
  "senior_dog_care",
  "rescue_dog_adjustment"
] as const;

export const DEFAULT_HUMAN_SCORE_THRESHOLD = 90;
export const DEFAULT_TOPIC_SCORE_THRESHOLD = 85;

export const BANNED_FILLER_PHRASES = [
  "In today’s fast-paced world",
  "In today's fast-paced world",
  "In today’s world",
  "In today's world",
  "When it comes to",
  "It is important to note",
  "It is worth noting",
  "Delve into",
  "Dive into",
  "Navigate the world of",
  "Unlock the secrets",
  "Unleash the power",
  "Game changer",
  "Ultimate guide",
  "Comprehensive guide",
  "One-stop shop",
  "Whether you are a seasoned dog owner",
  "From furry friends to",
  "Your furry companion",
  "Rest assured",
  "Look no further",
  "The good news is",
  "At the end of the day",
  "In conclusion",
  "To sum it all up",
  "This article will explore",
  "Let’s explore",
  "Let's explore",
  "Let’s dive in",
  "Let's dive in",
  "In this blog post",
  "Embark on a journey",
  "Taking your dog care to the next level",
  "Have you ever wondered",
  "Are you looking for",
  "Do you want to",
  "Did you know",
  "Imagine this",
  "Picture this",
  "Meet Max",
  "You won’t believe",
  "You won't believe",
  "This changes everything",
  "Stop scrolling",
  "The secret no one tells you"
] as const;
